export const FETCH_ALL_CARDS = 'FETCH_ALL_CARDS';
export const FETCH_ALL_CARDS_SUCCESS = 'FETCH_ALL_CARDS_SUCCESS';

export const FETCH_ELIGIBLE_CARDS = 'FETCH_ELIGIBLE_CARDS';
export const FETCH_ELIGIBLE_CARDS_SUCCESS = 'FETCH_ELIGIBLE_CARDS_SUCCESS';

export const UPDATE_CREDIT_CHECK_STATUS = 'UPDATE_CREDIT_CHECK_STATUS';
